### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split') when calling `npm run start` on fresh install

### ISSUE THREAD

**Issue by RikiVallen** [ChaDonSom/laravel-vite-template#3]
Error Log

```
failed to load config from F:\webdev\laravel-vite-template\vite.config.ts
error when starting preview server:
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (F:\webdev\laravel-vite-template\vite.config.ts:47:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at require.extensions.<computed> [as .ts] (F:\webdev\laravel-vite-template\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:61984:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (F:\webdev\laravel-vite-template\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:61992:17)
    at loadConfigFromFile (F:\webdev\laravel-vite-template\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:61911:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ChaDonSom** [comment]
Have you made sure to copy `.env.example` to `.env`?

**Comment by RikiVallen** [comment]
Thank you, that fixed it! If I had a dollar for every time I forgot to copy .env in past projects ha!
